### ISSUE TITLE
ActiveRecord 4.2 Compatibility

### ISSUE THREAD

**Issue by smathieu** [SchemaPlus/schema_validations#14]
This gem crashes with the new version of ActiveRecord (4.2)

Relevant stack trace:

```
/Users/simon/.rvm/gems/ruby-2.1.3@rainforest/gems/schema_validations-1.0.1/lib/schema_validations/active_record/validations.rb:103:in `block in load_column_validations': undefined method `text?' for #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x007f8250a40ea0> (NoMethodError)
	from /Users/simon/.rvm/gems/ruby-2.1.3@rainforest/gems/schema_validations-1.0.1/lib/schema_validations/active_record/validations.rb:95:in `each'
	from /Users/simon/.rvm/gems/ruby-2.1.3@rainforest/gems/schema_validations-1.0.1/lib/schema_validations/active_record/validations.rb:95:in `load_column_validations'
	from /Users/simon/.rvm/gems/ruby-2.1.3@rainforest/gems/schema_validations-1.0.1/lib/schema_validations/active_record/validations.rb:89:in `load_schema_validations'
	from /Users/simon/.rvm/gems/ruby-2.1.3@rainforest/gems/schema_validations-1.0.1/lib/schema_validations/active_record/validations.rb:8:in `block (2 levels) in extended'
```

Looks like the active_store_accessor https://github.com/jalkoby/active_store_accessor/issues/3 gem had to deal with a similar issue caused by active record renaming some internal methods.

**Comment by ronen** [comment]
@smathieu Thanks for pointing this out.  Yes, this gem hadn't yet been updated to work with (and test against) AR 4.2.

Luckily it was an easy fix (thanks for the pointer to jalkoby/active_store_accessor).  I've released a new version of this gem (1.1.0) which is compatible with AR 4.2.

**Comment by smathieu** [comment]
Wow, that was fast! Will give it a try.
