### ISSUE TITLE
Exception: `NoMethodError: undefined method `-' for nil:NilClass`

### ISSUE THREAD

**Issue by shosti** [SchemaPlus/schema_validations#37]
It looks like there's an exception that gets thrown for decimal columns with Postgres 9.5.2 and Rails 4.2.6. 

# Steps to reproduce:
1. Download https://files.emanuel.industries/foo.tgz (minimal Rails app with bug present)
2. Setup and start Rails console
3. `x = Foo.new`
4. `x.valid?`

# Expected result
No exception

# Actual result
Exception: https://gist.github.com/024278424d4673cfc1c0bb088231116a

I would guess this was introduced by https://github.com/SchemaPlus/schema_validations/pull/36 (I haven't had time to come up with a fix yet).

**Comment by ronen** [comment]
@shosti thanks for the exemplary bug report!  I've released v2.1.1 with this bug fixed.

**Comment by shosti** [comment]
That seems to have fixed it for us. Thanks for the prompt fix!
