### ISSUE TITLE
Multiple DB adapters of different types seems to break schema_validations

### ISSUE THREAD

**Issue by slieker-d** [SchemaPlus/schema_validations#58]
Working on a rails 4.2.x application that uses a default postgresql database.

Added a set of scoped models that establish a connection to a mysql database, and `schema_validations auto_create: false` to disable this gem for those models:

```
module MyModels
  class User < ActiveRecord::Base
    schema_validations auto_create: false
    establish_connection :mysql_production
  end
end
```

When I attempt to get the first instance of the User model, the following error occurs:

```
> MyModels::User.first
  MyModels::User Reverse Foreign Keys (14.1ms)          SELECT constraint_name, table_name, column_name, referenced_table_name, referenced_column_name
          FROM information_schema.key_column_usage
         WHERE table_schema = SCHEMA()
           AND referenced_table_schema = table_schema
         ORDER BY constraint_name, ordinal_position;

NoMethodError: undefined method `query' for #<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x0055f3628bca58>
Did you mean?  to_query
from /usr/local/lib/ruby/gems/2.3.0/gems/schema_plus_pg_indexes-0.1.12/lib/schema_plus_pg_indexes/middleware/postgresql/schema.rb:39:in `implement'
```

**Comment by slieker-d** [comment]
Sorry, this appears to be for the schema_plus_pg_indexes plugin, not schema_validations. Closing now.
